### PR TITLE
Integrate with gateway

### PR DESCRIPTION
**Pull request by hobinjk**
Use Authorization: Bearer jwt, and Accept headers. Add namespace to
config.

### CODE REVIEW

**Comment by hobinjk** [comment]
@benfrancis This PR combined with https://github.com/hobinjk/gateway/tree/rules-engine-integration puts the rules engine in `/rules-engine` on the gateway. It's not as clean as it could be because acquiring a JWT is an unsolved problem for now. Eventually I want to solve the problem by writing an OAuth2 client for the rules engine and authorization server for the gateway (the rules engine would then function as a confidential client when embedded and a public client when standalone). That's definitely something for next sprint though

**Comment by benfrancis** [comment]
This feels kind of incomplete and I don't think there's a pull request for the gateway side yet?

Seeing this develop, I'm still not convinced it's worth the effort of trying to implement this as a standalone app in a separate repo which can optionally be plugged into the gateway. It's good that we're discovering the issues of giving third party applications access to the gateway's API and I think an OAuth implementation is a great idea. However, I don't think solving these problems is our priority right now and I'd prefer it if we were focused on creating and testing a built-in rules engine with a great UI, which would be a lot easier if this was just part of the same app and repo as the gateway.

Perhaps IFTT integration or similar could separately show how an external rules engine could be integrated?

We also have the experimental voice UI and floorplan UI which will integrate with the same Web Thing API, the latter of which I plan to have its own entry in the gateway main menu just like the rules engine. I'd suggest that all three of these projects (voice, floorplan and rules engine) could be landed directly in the main gateway repo but turned off by default in settings until they are in a more advanced state.

I'm not opposed to extracting these things out into separate pluggable modules in the future, but at the moment I think it's an additional layer of abstraction which is adding unncessary complexity while we have other more pressing issues to worry about.

In the meantime, the rules engine could have its own directory in the main repo and have its own separate URL router if you prefer so that it's easier to extract later, but would be able to use the existing JWT middleware directly without needing to implement OAuth.

What do you think @andrenatal and @hobinjk ?

**Comment by hobinjk** [comment]
I understand that it is significantly easier for other people to test if they don't have to worry about acquiring a JWT or linking the rules engine as a local NPM module. I realize that as it stands, setting this up to run locally is prohibitively difficult. I'm going to take the next two hours to properly implement JWT storage and integrate as a module into the gateway as this approach is a bit too half-baked. I hope to show that it can be simple to talk to the gateway without invoking the nuclear option.

I strongly believe that developing the Rules Engine as a separate module is worth the occasional inconvenience. My belief is that allowing easy third-party integration is integral to building a community and that the best way to make sure that it is easy is to deal with it ourselves. That being said, I agree that implementing OAuth right now would distract from more pressing issues.

**Comment by benfrancis** [comment]
I definitely agree with your point about third party integration, but one thing that Mozilla has learned the hard way is that you need to define that point of integration very strictly, or you risk breaking third party integrations every time you change something (I'm thinking about Firefox add-ons).

We're currently in the process of defining one such add-on mechanism which is the adapter API, now that we have the experience of implementing a few different adapters and we're starting to need it. I do think there's likely to be demand for an add-on mechanism to extend the gateway's web app itself including the UI, but I'd argue it's still premature to be implementing that mechanism now.

Feel free to finish the solution you have in your head to demonstrate how it works, but what you call the "nuclear option" I'd call the "simplest possible solution" :)

**Comment by hobinjk** [comment]
I would consider the point of integration of this to be the WoT API + authorization, which is more WebExtension than Components.classes.

The only thing required to run this locally should now be `npm link` in the rules-engine and `npm link rules-engine` in the gateway (or `yarn link`)

**Comment by hobinjk** [comment]
I agree that the current integration leaves much to be desired. I think that creating an add-on system is a good long-term goal. Until then, having this around as a module with some areas of tight coupling with the gateway shows us what an add-on system would need and shows potential developers how to create a reasonably complex stand-alone project using the gateway.

**Comment by dhylands** [comment]
I was thinking about this, and we definitely don't want to tie whether a rule can run to be tied to whether the user is logged into the gateway or not.

I think that the rule itself should be tied to a user, and it should have some type of token which is tied to the user and not need to be changed just because the user changes their password. Perhaps something along the lines of how ssh password-less login works.

**Comment by hobinjk** [comment]
@dhylands The way I imagine it going is that once OAuth2 is implemented, the rules engine can use the same tokens locally that would normally be handed out over OAuth2. These tokens would be tied to a specific user account without being destroyed on log-out by design

**Pull request merged**
