### PR TITLE
Basic Implementation

### PR DESCRIPTION
**Pull request by hobinjk**
- [x] Rules, Actions, and Triggers
- [x] POST /rules
- [x] GET /rules
- [x] DELETE /rules
- [x] PUT /rules
- [x] Tests
- [x] Engine
- [x] UI

### CODE REVIEW

**Comment by hobinjk** [comment]
This PR is rapidly growing in scope but it's finally reached a nice enough stopping point. I'm going to file follow-up issues for a few missing things but for now this is a pretty complete basic implementation.

Closes #1, #2, #4, #6, #7, #9

**Comment by hobinjk** [comment]
Closes #12 now too

**Comment by benfrancis** [comment]
FWIW the adapter system started out in its own GitHub repo as a separate thing, then we merged it into the main app. We should think about how to integrate this with the main app but keep it in a separate repo if desired. I also think we should split out some of the Raspberry Pi-specific OS code from the current gateway repo, so our source code structure is still quite fluid!

**Comment by hobinjk** [comment]
The way I imagine integrating it with the gateway is to add a line in `src/router.js` approximately equivalent to `app.use('/rules-engine', require('../../rules-engine/index.js'));`. The current code doesn't quite work with this (some paths need to be absolute instead of relative).

**Comment by hobinjk** [comment]
As you said, I'm going to land this to have a basic prototype done for this sprint. I've added a note to the README that this is an MVP and not production-ready

**Pull request merged**
